apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    isDefault: true
    access: proxy
    url: http://influxdb:8086
    database: gateway-benchmarks
    jsonData:
      version: SQL
      insecureGrpc: true
      httpMode: POST
